const CATEGORIES_ACTION_TYPES = {
  FETCH_CATEGORIES_START: 'category/FETCH_CATEGORIES_START',
  FETCH_CATEGORIES_SUCCESS: 'category/FETCH_CATEGORIES_SUCCESS',
  FETCH_CATEGORIES_ERROR: 'category/FETCH_CATEGORIES_ERROR',
};

export default CATEGORIES_ACTION_TYPES;
